-- MySQL Script generated by MySQL Workbench
-- Sun Jul 12 08:48:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wpes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wpes` ;

-- -----------------------------------------------------
-- Schema wpes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wpes` DEFAULT CHARACTER SET utf8 ;
USE `wpes` ;

-- -----------------------------------------------------
-- Table `wpes`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wpes`.`users` ;

CREATE TABLE IF NOT EXISTS `wpes`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `full_name` VARCHAR(255) NULL,
  `last_login` DATETIME NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `token_reset` VARCHAR(255) NULL,
  `token_resetexpired` DATETIME NULL,
  `activation_token` VARCHAR(255) NULL,
  `refresh_token` TEXT NULL,
  `refresh_tokenexpired` TIMESTAMP NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wpes`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wpes`.`device` ;

CREATE TABLE IF NOT EXISTS `wpes`.`device` (
  `iddevice` INT NOT NULL AUTO_INCREMENT,
  `deviceId` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  `code_registration` VARCHAR(255) NULL,
  `access_key` VARCHAR(255) NULL,
  `last_ipaddress` VARCHAR(255) NULL,
  `created_at` VARCHAR(255) NULL,
  `updated_at` VARCHAR(255) NULL,
  PRIMARY KEY (`iddevice`),
  INDEX `fk_device_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_device_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wpes`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wpes`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wpes`.`sensor` ;

CREATE TABLE IF NOT EXISTS `wpes`.`sensor` (
  `idsensor` INT NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NULL,
  `type_sensor` VARCHAR(45) NULL,
  `value` FLOAT NULL,
  `device_iddevice` INT NOT NULL,
  PRIMARY KEY (`idsensor`),
  INDEX `fk_sensor_device1_idx` (`device_iddevice` ASC) ,
  CONSTRAINT `fk_sensor_device1`
    FOREIGN KEY (`device_iddevice`)
    REFERENCES `wpes`.`device` (`iddevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wpes`.`log_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wpes`.`log_action` ;

CREATE TABLE IF NOT EXISTS `wpes`.`log_action` (
  `time` TIMESTAMP NOT NULL,
  `action` VARCHAR(255) NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`time`),
  INDEX `fk_log_action_device1_idx` (`device_id` ASC) ,
  CONSTRAINT `fk_log_action_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `wpes`.`device` (`iddevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
